import type { Metadata } from 'next'
import './globals.css'
import Header from './Layout/header'
import Footer from './Layout/footer'
import { Montserrat } from 'next/font/google'
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css";

const montserrat=
Montserrat({
  subsets:['latin'],
  weight:['400','700']
})

//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Instanpe',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {        media: '(prefers-color-scheme: light)',
        url: '/favicon.png',
        href: '/favicon.png',
      },      {        media: '(prefers-color-scheme: dark)',
        url: '/favicons.png',
        href: '/favicons.png',
      },
    ],
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='container mx-auto '>
        {/* <div className='container mx-auto w-[100%]'> */}
        <div className={montserrat.className}>
          <ToastContainer position="top-right" autoClose={3000} hideProgressBar />
          <div className=''>
          <Header/>
             {children}
           <Footer/>
          </div>
         
        </div>
      </body>
    </html>
  )
}
